epochs: 400

train_path: ./src/../data/sample_offres.csv
val_frac: .1
n_elements: -1
max_seq_length: 512
frac_msk: 0.15
batch_size: 16
shuffle: True
learning_rate: 0.00001
patience: 4
optimizer: AdamW
loss_fn: CrossEntropyLoss
train_step: -1
val_step: -1
model_name: pre_trained_bert_1
weights_path: ./src/mlm/weights/
checkpoint_frequency: 2
